import type { ReactNode } from "react";
import { Image, StyleSheet, View, type StyleProp, type ImageStyle } from "react-native";

import { radius, space, useTheme } from "../../theme";
import { imageMeta, images, type ImageKey } from "../../theme/images";

import { Icon } from "./Icon";
import { Text } from "./Text";

interface AppImageProps {
  name: ImageKey;
  width?: number;
  height?: number;
  // Monochrome line art is recolored with this color.
  tint?: string;
  // Informative images need a label; decorative ones stay silent.
  accessibilityLabel?: string;
  // Shown in release builds while the image hasn't been generated yet.
  fallback?: ReactNode;
  style?: StyleProp<ImageStyle>;
}

// Image slot by registry key (src/theme/images.ts, generated by
// processar_imagens.py). Until the file exists: a dashed placeholder with
// the file name in dev, the `fallback` (or nothing) in release.
export function AppImage({
  name,
  width,
  height,
  tint,
  accessibilityLabel,
  fallback,
  style,
}: AppImageProps) {
  const { colors } = useTheme();
  const meta = imageMeta[name];
  const source = images[name];
  const size = { width: width ?? meta.width, height: height ?? meta.height };

  if (!source) {
    if (!__DEV__) return <>{fallback ?? null}</>;
    return (
      <View
        style={[
          styles.placeholder,
          size,
          { backgroundColor: colors.placeholder, borderColor: colors.borderStrong },
        ]}
        accessibilityElementsHidden
        importantForAccessibility="no-hide-descendants"
      >
        <Icon name="image-outline" size="lg" color={colors.textSubtle} />
        <Text variant="caption" tone="subtle" align="center" numberOfLines={2}>
          {meta.file} · {size.width}×{size.height}
        </Text>
      </View>
    );
  }

  return (
    <Image
      source={source}
      resizeMode="contain"
      accessible={!!accessibilityLabel}
      accessibilityLabel={accessibilityLabel}
      style={[size, tint ? { tintColor: tint } : null, style]}
    />
  );
}

const styles = StyleSheet.create({
  placeholder: {
    alignItems: "center",
    justifyContent: "center",
    gap: space.xs,
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: radius.md,
    padding: space.sm,
  },
});
