// Generated by .claude/skills/app-design/scripts/processar_imagens.py
// Do not edit by hand: run the script again after saving images to design/img-original/.
import type { ImageSourcePropType } from 'react-native';

export const images = {
  notebookCover: null,
  emptyTransactions: null,
  emptyGoals: null,
  emptyDebts: null,
  emptyGrocery: null,
  emptyVehicles: null,
} satisfies Record<string, ImageSourcePropType | null>;

export const imageMeta = {
  notebookCover: { file: 'capa_caderno.png', width: 220, height: 160, color: null, effect: null, repeat: false, blend: 'normal' },
  emptyTransactions: { file: 'vazio_lancamentos.png', width: 240, height: 180, color: null, effect: null, repeat: false, blend: 'normal' },
  emptyGoals: { file: 'vazio_metas.png', width: 200, height: 150, color: null, effect: null, repeat: false, blend: 'normal' },
  emptyDebts: { file: 'vazio_dividas.png', width: 200, height: 150, color: null, effect: null, repeat: false, blend: 'normal' },
  emptyGrocery: { file: 'vazio_mercado.png', width: 200, height: 150, color: null, effect: null, repeat: false, blend: 'normal' },
  emptyVehicles: { file: 'vazio_veiculos.png', width: 220, height: 150, color: null, effect: null, repeat: false, blend: 'normal' },
} as const;

export type ImageKey = keyof typeof images;
